spring:
  datasource:
    url: jdbc:h2:mem:bcamp2024
    username: bcamp2024
    password:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create # validate | update | create | create-drop
    properties:
      hibernate:
        format_sql: true # show logs
  h2:  # display acess via browser
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

# *.yml is automatically detected, but with -dev.yml not