spring:
  datasource:
    url: jdbc:postgresql://172.18.0.2:5432/postgres
    username: postgres
    password: example
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create # update 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
